apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: confluent-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: AgAbKnnCazDbWgkrFfNm57s+V7tid41nQwf5WGs201tbCppJSkapvsXzQ1Ntpso4aS2R6eJCXYVWQW/StZ3QFm4EI2a+Q5mpDq55AwRuVW1FD+XAPL0yh1oaMMoadoxp5OYqg/QFOgJV/LDtTgQ/EdUDNn9jSLl4A5XmZ2mDkGI8GQ3ZnkfZ1Bvc3MlqVrCm1AOmj2LFRvMX6dCMTIqwu2TIx4qFshFV0WDjmkyhf4L0r0XWgtTWYGLUa+foi2dJJfXy4/L1llzfsmum7pa31YBelA+3E+MrPW+Zjj4Qd2WNHKnNdtSRi1dUfpj0R+9pnGMv0YPH8o6sj/9TQp/7/2JtQGV75V8v6jxz03SSAhn4Er6oOU9rdBqFalRUE9XokzilDxyOpNvboHPcswpzC9OhhY098ncDeNdpuUIqSrQJYmaOALt1R7J5gZHxgySd33lJ+2lGWQTCXP2LtgEcyPym4hkvJVeETiiBRZXGL8xryGk/rbA00ACtGywg6TifLWfmCJanNPHN5mHkDJQj6d6RK3uyJ0lYz9dvHeDLZ0Mh1kytg++G+PXTpoKElApQy9ZYV5ZQb2H6eCip3MiJFFCREfPCBKwOBH7Fufu3UiS3vyWou051EhB3/yneY4ooEESbS2OPOdCd5tjdmA2U/r+8vt+leNXsAoi86r+b3bD1dlqm3IVcqy/BSEG3qiYQEftKl/csjPrj6w5iU8XNgEnzUfImVJQEAy8n4fKuCO/U2GfRJ9ThZWhYJ2oKZpKJ/1DuKlGcyq1AF2j74sCyPIwj
    username: AgAQs3dRIPzA4ZEmEwiCW6HxLYPsRBmNjpiNUWLvh2bYFvBpqurKLnN5Qb3q8TiUyhwSIsEZtmCwq8pvqmDmpVhpb1reI6coZhQv0zP5XHgZXohp5lWklnGcRazlhzU9iq3CuIJcdXJtXNMSiAB5JTW4Qgtt19jVUojjuPJApfK8XAambcqbDEragtSc78yN+SL+IGl1JdQbPJ0IawH9aE1IotMbGICuxeY8bqFeYg72oI5ETyKbB+AaPTR5ujdDagiCroKpLnsX4Ofu0gabPPWBdwrvJjf+9pCpMa2fRx3fYaOYYruXwtdDtF1yM7Qacdt1NRHDaMEuRSKe5mLIMKGElno5+zA2bdgnbLymMoa2jlYOi7OK7zBa+9S7e3m2In1Iz1Rl6nkI98q6dS2wg73WFrPrg8PJQbHB3QgXVwNpGEEICPBP0Kx4oOxuL2Ux/wUsSQ1R0MhJ9zWfMuPH/WtskPSx7p9ZVbJ9N7M3Kq6C97epATlygbwRbSGl9DHVDrsEM+CMad6RMWxb/xrqP1szsZI6nM5oo81Uz0syVNnUTqYeXVroF381WePoFtoZmxYQuvUPiOW0NwlsENLJ+GR9Pyu3UezLhzEOqYiUCjKtWgHSK5/X8AQdQvgQKa01rA/l4R9A3sqxsNuU7rK6JgTqy17sn72TinnQnRCvj4ZmfeUrkHZicHk62igH35rNTY1m1uSQITu5TpbX3UZ9uuA8
  template:
    metadata:
      creationTimestamp: null
      name: confluent-credentials
      namespace: monitoring
    type: Opaque

