apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack-app-webhook
  namespace: monitoring
spec:
  encryptedData:
    slack_api_url: AgAUB+iFG8O968V9m3+IyWr8lmwrzNqL2zxZZ6pN3xh0vV5flL0S7+pK43hLyDAW3exWbKWEh7uMzOpsrrVeCdmVa2qPb4TZkMFkYNFWf6pPFaKSLWcUE9KIX7WaBbBx51qp2FlQuiyRsmM0sPJbwnCDesn2AWGrKBHIwh2t7e0dPGi+C+NsSAIoB0OgCUoOpz+rKcdg1SqXT7fy7eK6oGXayg1HceKDlb88vMgubPyL9aZKw2SFazFmDty3riWt4no6laFuyGswyWujwIaZIOZsb5aaImlx7cmTpd2GxPKXJGJuRwHLe3YBGce/LF8gKo2kVbr/aLz6DtScCm795yfpjmKtVyoi36lkYsRxGY+oCk9r59mEaEkL30sQvwVVjRomwLrAn75P1h5QnIo1UzmYIw5e0ww71amjlawMIB8B3HhJgd7UjL8F2dsrJFbkFWWdDFPFjyjoF7oa2SkRr+d75XlokdMGH4rBlnS9YJ+NujkJGqBd87O/BFQfYkvO7Gv3n6Ncq6GA1iLQfO8iQ3syhKKUREmx9p5E4Z0rToJzMBsoYVqeuYUUTxMNcE0BTcXpb0rbCbx47057Y4BWaUtmnSAFPsd9EnNWNYruDhQukAGHTBusMRVe2zpN/bkUzs5iblhxHW4JdTUDCs1cLHv34J9ihvyHxb73st8SYRiqVrBsvEpJCekc+mldFm8sjsv231MalmLGU6SgVqaUALO+65xRJNh6zJi4iAHwifQAsPojutUIndfu5dgwavO4FYsfbAeLf2GMJ16QpgMcAxXr7zlnSqr2toeg9PLGuNajTmM=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack-app-webhook
      namespace: monitoring
    type: Opaque

