apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: confluent-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: AgBxl2CKlZOcL6yfU7LZVF5bp9fIKAtWW5J9BwXZHARCHuun5AgZPvaNUJXXclIClysvHF+VJGCtIVtP4U0Fx+ON0YtZ0VC/tiYK4YM8i2aueOcWjzCGrF2sgFzL5I3Mblu8HFtHuKgWUSbnOgABGbkpk7EsE6dqsysR2S0IW+Fc7Pj0JLTKBuaJPTWQUDrC721GjG2UMWleXHITv9+7JVfduu3Z5jDkmy/Bn/fxU9vNZHUYaemKNOGsxHhl6eWav7Wiu3i5hZtGv3hlyvffJruHH77O4EJ1Lw+OBYJSiKABYdUsVx14nzyspPNtUtC5mYnBQ1uC9DVafaOQ7SSMTzaEUJug4LqIHVgItEsy1ZnXa2Qeo96To4GzJJXv/k0E/O326pnVw+uD24uMrObmnZxg4RwkR3ebsOlZt4HKR8Nfynt/jNqx25EHyrmeroskUOCOzNO1N1Ca2sdeAmne/L7mwdZ7GGhf2xVP2aGnieG6bDfLKNxn/JfdchgHHC/cY9e58/RqSacNTX+xqjZco/oJ245LEh3MJevHM/z3dsOhHqJCdaqfO6OrgfylKlsptDm0Bdp8tK4iMSUeONKbZIosc9y0q1F2dkWPqXXAC375pYRyieuLwufvZyiAMgMEk0mPOD1tcRKrDqBjskWZ1k2g7WhkxeeYk4hdwl1cGGBaSySvjU6LaHk7Of8dmRgdXsVRm5L0f/2Bu8WdWDcKA/47UX5VSBz2QjfNnypOoTQqGMWHc/IqVp5NHogRgNf//ddYfIYrCuLiQQLwOwIvSCGp
    username: AgCQ0kmuBHQDmnLijrbQhF5zCkEO7Zk0aPo9CdeqzRjxkTxlCwIFFrD6/up/M8Ts6t1famsAHbY88bUhTdr3Q+NyfSmNIM6OHssRR5zl+e+UPWg7PeaoVrUD3N48c4L3YEbSqWTcK1koyRdBpUFlQ1b6n4Ad2nbVXrDnQRUKB/F2xFwlmx27iJZc1KIu4iYgKNwTulLMeLXJVIus1j7K6R6+91Fqvi8z6nRjO87X6ssy9ggB7mwr5QPI0dHYIINFMmmvoVU9P0bX1EbJQCAC/adPhunlPk37KnnpQj7bCndSa75whlIUeXvrJec2US6FN1UFu9XUfQQ1FNpqvY44QpgNY972uCvHYtB5o4Q9/5RiJDBFkDK3wi95KTR7EfbWyVd1FkpIbKcLCnEJYuIwAcm5KCLl8gAfNVx/zEUwYWWJ1nsIan8ANM4MXFx43+fpTAXG63dG2B2mSw35WiZv4DvVNEyuuaIiYN3PHiruDiwRL7hX0/h1e1Fwe132aNqWIk/UCa+39hJtzqzrpiXpGGS5TIBkm9C6qIvYc+HdjTmvh/xlo916pIAVEqCYipeJ+uz83z9uA8VSNoueg1X/zprXxinfZCTeUnJSbzMDxSi3dTqACboJOY2hEsuURQtOzpeIQkXbxvbfqEIdXzCtEu4d62wO3ySNsLn5u7Vx4ZNb9r1uGQ0WHu1cwS41qxSEcd3eB4HNkQcq6yobcW0O5S6I
  template:
    metadata:
      creationTimestamp: null
      name: confluent-credentials
      namespace: monitoring
    type: Opaque

